<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Cogana.Admin.Dominio\Cogana.Admin.Dominio.csproj" />
    <ProjectReference Include="..\Cogana.Admin.Aplicacion\Cogana.Admin.Aplicacion.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Velopack" Version="1.2.158" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
